name: Publish package to the Maven Central Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 # v4.0.0

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_SECRET_KEY }}" > private.key
          gpg --batch --passphrase "${{ secrets.GPG_SECRET_KEY_PASSWORD }}" --import private.key
          rm private.key

      - name: Publish package
        run: ./gradlew publish
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_SECRET_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
